version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.3.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "Gemfile.lock" }}
          - dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec spec/
